name: Lint and Format Check

on:
  pull_request:

jobs:
  lint:
    name: Run Ruff and Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or the version you use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Run Ruff
        run: ruff .

      - name: Run Black (check only)
        run: black --check .