name: Lint and Format Report

on:
  pull_request:

jobs:
  lint:
    name: Run Ruff and Black (informational)
    runs-on: ubuntu-latest
    continue-on-error: true  # Ensures the job doesn't fail the PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Run Ruff (report only)
        continue-on-error: true
        run: |
          echo "## Ruff Output" >> $GITHUB_STEP_SUMMARY
          ruff . | tee -a $GITHUB_STEP_SUMMARY

      - name: Run Black (check only)
        continue-on-error: true
        run: |
          echo "## Black Output" >> $GITHUB_STEP_SUMMARY
          black --check . | tee -a $GITHUB_STEP_SUMMARY